version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: soc_dashboard
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
